language: php
php:
  - 7.2

cache:
  directories:
    - node_modules
    - vendor

before_install:
  - nvm install stable

install:
   - npm install --production
   - npm run storybook:init

before_script:
  - gem install sass
  - mkdir dist
#  - gem install travis
#  - travis login --pro --debug --github-token $PA_TOKEN
  - composer require couscous/couscous

script:
  - npm test && npm run build && vendor/bin/couscous generate && npm run storybook:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PA_TOKEN
  local-dir: .couscous/generated
  keep-history: true
  on:
    branch: test-24
