# Project language
language: php
php:
  - 7.2

# Cache node packages
cache:
  directories:
    - node_modules

# Get a stable version of node.js
before_install:
  - nvm install stable

# Install dependencies and couscous
install:
   - composer require couscous/couscous
   - npm install

# Install sass and create the dist directory
before_script:
  - gem install sass
  - mkdir dist

# Run tests, build and deploy
script:
  - npm test && npm run build && npm run deploy

# Update code coverage
after_script:
  - travis_retry npm run coveralls
