# Project language
language: php
php:
  - 7.2

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PA_TOKEN
  keep-history: true
  on:
    branch: master

  # Cache node packages
  cache:
    directories:
      - node_modules

  # Get a stable version of node.js
  before_install:
    - nvm install stable

  # Install dependencies and couscous
  install:
     - composer global require couscous/couscous
     - npm install --production

  # Install sass and create the dist directory
  before_script:
    - gem install sass
    - mkdir dist

  # Build and deploy
  script:
    - npm test && npm run build && npm run deploy
